#!/usr/bin/env bash
# Orquesta la construcción del proyecto con Antigravity CLI en modo no interactivo, por etapas.
cd "E:/PROYECTOS DE TESIS/UPN-1-ING-SISTEMAS/FerreMax_App" || exit 1
AGY="/c/Users/david/AppData/Local/agy/bin/agy.exe"
MODEL="gemini-3.1-pro-high"
LOG=".agents/driver.log"
STATUS=".agents/status.txt"
COMMON="El directorio del proyecto es E:\PROYECTOS DE TESIS\UPN-1-ING-SISTEMAS\FerreMax_App y el brief está en E:\PROYECTOS DE TESIS\UPN-1-ING-SISTEMAS\FerreMax_App\BRIEF.md. Usa siempre rutas absolutas dentro de ese directorio; no busques archivos fuera de él ni uses tareas en segundo plano para buscar. Trabaja únicamente dentro de esa carpeta. Lee BRIEF.md completo antes de actuar y respeta sus reglas (sección 8): nada de métricas inventadas en la interfaz, etiqueta 'Datos simulados', clientes solo por código anónimo, todo en español. Verifica tu trabajo ejecutándolo (instala dependencias, corre el servidor o las pruebas y comprueba salidas reales). Si algo falla, corrígelo antes de terminar. Al final escribe un resumen breve: archivos creados, cómo lo verificaste y qué quedó pendiente."

run_step () {
  local n="$1"; local prompt="$2"; local cont="$3"
  echo "===== ETAPA $n · inicio $(date '+%H:%M:%S') =====" >> "$LOG"
  echo "ETAPA $n EN CURSO $(date '+%H:%M:%S')" > "$STATUS"
  if [ "$cont" = "1" ]; then
    "$AGY" -p "$prompt" --continue --add-dir "$PWD" --dangerously-skip-permissions --model "$MODEL" --print-timeout 50m --output-format stream-json 2>>"$LOG" | python -u .agents/fmt_stream.py >> "$LOG"
  else
    "$AGY" -p "$prompt" --add-dir "$PWD" --dangerously-skip-permissions --model "$MODEL" --print-timeout 50m --output-format stream-json 2>>"$LOG" | python -u .agents/fmt_stream.py >> "$LOG"
  fi
  local rc=${PIPESTATUS[0]}
  echo "===== ETAPA $n · fin $(date '+%H:%M:%S') · exit $rc =====" >> "$LOG"
  echo "ETAPA $n TERMINADA exit $rc $(date '+%H:%M:%S')" > "$STATUS"
}

run_step 1 "$COMMON ETAPA 1 de 7, sección 7.1 del BRIEF: crea el backend en backend/ con Python 3.12 y FastAPI, SQLAlchemy y SQLite para desarrollo (deja el cambio a PostgreSQL parametrizado por variable de entorno). Implementa el modelo de datos de la sección 5, un script backend/seed.py que siembre productos, clientes, comprobantes, detalle, reglas y popularidad desde datos/datos_simulados_prototipo.json (genera códigos de cliente anónimos CLI-### y fechas verosímiles), y los endpoints GET /api/productos, GET /api/productos/{sku} y GET /api/categorias. Crea backend/requirements.txt y backend/README.md con cómo ejecutar. Verifica: instala dependencias en un entorno virtual backend/.venv, ejecuta el seed, levanta uvicorn en el puerto 8000 en segundo plano, consulta los endpoints con curl y muestra las respuestas, y luego detén el servidor." 0

run_step 2 "$COMMON ETAPA 2 de 7, sección 7.2: implementa en backend/ el servicio de recomendación con los dos modos de la sección 2 y el conmutador global en la tabla configuracion (modo_activo CONV o ML, k, soporte_min, confianza_min, lift_min, peso_contenido). Modo CONV: más vendidos y misma categoría. Modo ML: TF-IDF con scikit-learn sobre nombre, marca, categoría, subcategoría, uso y palabras_clave para POST /api/buscar-necesidad, y reglas de asociación (usa las reglas sembradas y además un entrenador con mlxtend FP-Growth sobre los comprobantes, POST /api/admin/modelo/reentrenar) para GET /api/recomendar?sku= y POST /api/recomendar/carrito, ordenando por confianza por lift y completando hasta K con popularidad, nunca productos con stock 0. Endpoints GET y PUT /api/admin/config y GET /api/admin/reglas. Verifica con curl: la misma consulta 'pintar un dormitorio' y el mismo carrito deben dar resultados distintos al cambiar el modo con PUT /api/admin/config, y muéstralo en el resumen." 1

run_step 3 "$COMMON ETAPA 3 de 7, sección 7.3: implementa el registro de eventos y los indicadores de la sección 3. Tablas sesiones_evaluacion y registro_eventos con los once campos exactos. Endpoints POST /api/eventos, POST /api/admin/sesiones (iniciar y finalizar, con codigo_cliente, escenario ESC-01 a ESC-08, condicion y orden A o B), GET /api/admin/eventos con filtros por sesión, cliente, condición y tipo, GET /api/admin/indicadores que calcule por sesión el tiempo de selección en segundos como diferencia entre CONFIRMACION_CARRITO e INICIO_BUSQUEDA, recomendaciones mostradas, aceptadas (origen RECOMENDACION de la última lista mostrada, descontando retiros) y Precision@5 de sesión, y agregados por condición (media, mediana, desviación estándar, n). POST /api/carrito/confirmar que cree el pedido con detalle y origen de cada producto y registre CONFIRMACION_CARRITO. Verifica simulando con curl una sesión completa en cada condición y mostrando los indicadores calculados." 1

run_step 4 "$COMMON ETAPA 4 de 7, sección 7.4: crea el frontend de la tienda en frontend/ con React, Vite y Tailwind, reproduciendo fielmente los archivos de diseno_stitch/: 01_inicio, 02_busqueda_por_necesidad, 03_detalle_producto, 04_carrito, 13_confirmar_pedido, 14_pedido_registrado, 15_mi_cuenta y 16_login. Reutiliza las clases y la estructura del HTML exportado; puedes usar las mismas URL de imágenes. Conecta cada pantalla al backend: el buscador llama a /api/buscar-necesidad, el bloque Recomendados y Complementa tu compra a /api/recomendar, el carrito a /api/recomendar/carrito y /api/carrito/confirmar, y el frontend envía a POST /api/eventos todos los tipos de evento de la sección 3 con marcas de tiempo en milisegundos, incluyendo el origen de cada producto agregado y la posición de la recomendación. La etiqueta 'Modo: Machine Learning' o 'Modo: Convencional' debe reflejar el modo activo real leído de /api/admin/config. Muestra 'Datos simulados' en el pie. Verifica: npm install, npm run build sin errores, y levanta backend y frontend juntos para comprobar con curl que el frontend sirve y que las llamadas al API responden." 1

run_step 5 "$COMMON ETAPA 5 de 7, sección 7.5: agrega en frontend/ el panel de administración bajo /admin con login simple por rol (usuario y contraseña en variables de entorno del backend, sesión con token), reproduciendo diseno_stitch/05_panel_recomendador, 06_panel_evaluacion, 07_panel_resumen, 08_panel_productos_inventario, 09_panel_pedidos, 10_panel_clientes, 11_panel_registro_eventos y 12_panel_configuracion. Todo dato mostrado debe venir del backend: conmutador de modo con PUT /api/admin/config, sesión de evaluación con POST /api/admin/sesiones, tabla de reglas de /api/admin/reglas, indicadores y gráfico de /api/admin/indicadores (usa Recharts o Chart.js), registro de eventos con filtros y exportación CSV, productos con stock bajo, pedidos con estados, clientes por código y configuración de parámetros. Elimina cualquier número decorativo del diseño que no salga de un cálculo. Verifica con build y con una prueba manual vía curl del flujo: cambiar modo, iniciar sesión de evaluación, registrar eventos, consultar indicadores." 1

run_step 6 "$COMMON ETAPA 6 de 7, sección 7.6: crea backend/evaluacion_offline.py y el endpoint POST /api/admin/evaluacion-offline que implementen la Capa 1 de la sección 3: ordenar los comprobantes por fecha, reservar el 20 por ciento más reciente como conjunto de prueba, entrenar las reglas solo con el 80 por ciento restante, y para cada comprobante de prueba con dos o más productos ocultar uno al azar con semilla fija 42, generar 5 recomendaciones con el modo CONV y 5 con el modo ML a partir del resto de la canasta, y calcular Precision@5 igual a aciertos entre 5 y Recall@5 igual a aciertos entre 1. Exporta un CSV con una fila por comprobante y modo (comprobante, producto_oculto, top5, acierto, precision5, recall5) en backend/salidas/ y devuelve el resumen con medias por modo y n. Verifica ejecutándolo sobre los datos sembrados y muestra el resumen real obtenido." 1

run_step 7 "$COMMON ETAPA 7 de 7, sección 7.7: escribe README.md en la raíz con la arquitectura, cómo instalar y ejecutar backend y frontend, credenciales de demostración, y cómo correr la evaluación offline; crea demo.sh y demo.ps1 que siembren datos y levanten backend y frontend. Revisa el proyecto completo contra BRIEF.md: comprueba que el registro de eventos tenga exactamente los once campos, que no haya métricas inventadas en ninguna pantalla, que la etiqueta Datos simulados esté visible, y que el conmutador de modo cambie realmente las recomendaciones. Ejecuta demo.ps1, verifica con curl que todo responde, detén los procesos y entrega un informe final con la lista de archivos, los endpoints, lo verificado y lo pendiente." 1

echo "TODAS LAS ETAPAS TERMINADAS $(date '+%H:%M:%S')" > "$STATUS"
